DROP TABLE "ACCESS_LOG"; /*주희 추가*/
DROP TABLE "PROF_IMAGE"; /*주희 추가*/
DROP TABLE "APPROVAL_LINE";

DROP TABLE "SUMMERNOTE_IMAGE";
DROP TABLE "ATTACH";
DROP TABLE "UPLOAD";
DROP TABLE "LOVES";
DROP TABLE "CMT";
DROP TABLE "BOARD";
DROP TABLE "NOTIC";
DROP TABLE "ANONY";
DROP TABLE "UN_CMT";


DROP TABLE "TAG";
DROP TABLE "MAIL_SUMMER_IMAGE";
DROP TABLE "MAILSTATUS";
DROP TABLE "MAIL_ATCH";
DROP TABLE "RECEIVERS";
DROP TABLE "MAIL";
DROP TABLE "PERSONAL_ADDR";
DROP TABLE "ADDR_GROUP";  
DROP TABLE "EMP_ADDR";

DROP TABLE "ATTENDANCE";
DROP TABLE "SCHEDULE";
DROP TABLE "ANNUAL";  -- 삭제하고 없애야ㅐ함
DROP TABLE "Early"; -- 삭제하고 없애야ㅐ함
DROP TABLE "VACATION";  -- 삭제하고 없애야ㅐ함

DROP TABLE "RETIRED";
DROP TABLE "EMPLOYEES";
DROP TABLE "DEPARTMENTS";
DROP TABLE "POSITION";

DROP TABLE "DOCUMENT";
DROP TABLE "DOCUMENT_ATCH";
DROP TABLE "DOCUMENT_FORM";
DROP TABLE "DOCUMENT_TEMP";


CREATE TABLE "POSITION" (
	"JOB_NO"	NUMBER		NOT NULL,
	"JOB_NAME"	VARCHAR2(10 BYTE)		NOT NULL,
    CONSTRAINT PK_POSITION PRIMARY KEY(JOB_NO)
);

CREATE TABLE "DEPARTMENTS" (
	"DEPT_NO"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR2(40 BYTE)		NOT NULL,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY(DEPT_NO)
);

CREATE TABLE "EMPLOYEES" (
   "EMP_NO"       NUMBER      NOT NULL,
   "EMP_PW"       VARCHAR2(64 BYTE)      NOT NULL,
   "NAME"           VARCHAR2(50 BYTE)      NOT NULL,
    "BIRTHYEAR"     VARCHAR2(4 BYTE) NOT NULL,  
    "BIRTHDAY"      VARCHAR2(4 BYTE) NOT NULL, 
   "JOIN_DATE"       DATE      NOT NULL,
   "PROF_IMG"       CLOB      NULL,
   "INFO_MODIFY_DATE"   DATE      NULL,
 --  "STATUS"       VARCHAR2(10 BYTE)      NOT NULL, --삭제
   "SALARY"       NUMBER      NULL,
   "JOB_NO"       NUMBER,
   "DEPT_NO"      NUMBER NOT NULL,
   "PHONE"        VARCHAR2(11 BYTE) NULL,
   "SESSION_ID" VARCHAR2(32 BYTE),        -- 추가
   "SESSION_LIMIT_DATE" DATE,             -- 추가
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY(EMP_NO)
);

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT FK_EMPLOYEES_USERS FOREIGN KEY(JOB_NO)
        REFERENCES POSITION(JOB_NO)
            ON DELETE SET NULL;
            
ALTER TABLE EMPLOYEES
    ADD CONSTRAINT FK_EMPLOYEES_DEPT FOREIGN KEY(DEPT_NO)
        REFERENCES DEPARTMENTS(DEPT_NO)
            ON DELETE SET NULL;

CREATE TABLE "RETIRED" (
	"EMP_NO"	    NUMBER		NOT NULL,
	"NAME"	        VARCHAR2(50 BYTE)		NOT NULL,
	"PHONE"	    VARCHAR2(11 BYTE)		NOT NULL,
	"BIRTHYEAR"	    VARCHAR2(4 BYTE)		NOT NULL,
	"BIRTHDAY"	    VARCHAR2(4 BYTE)		NOT NULL,
	"JOIN_DATE"	    DATE		NULL,
	"RETIRED_DATE"	DATE		NULL,
    "JOB_NO"       NUMBER,
    "DEPT_NO"      NUMBER NOT NULL,
    CONSTRAINT PK_RETIRED PRIMARY KEY(EMP_NO)
);

CREATE TABLE "Early" (
	"EMP_NO"	    NUMBER		NOT NULL,
	"EARLY_CONTENT"	VARCHAR2(70 BYTE)		NULL,
	"EARLY_DATE"	VARCHAR2(40 BYTE)		NULL
);

ALTER TABLE "Early"
    ADD CONSTRAINT FK_Early_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE CASCADE;

CREATE TABLE "VACATION" (
	"EMP_NO"	        NUMBER		NOT NULL,
	"VACATION_CATEGORY"	VARCHAR2(20 BYTE)		NULL,
	"VACATION_START"	DATE		NULL,
	"VACATION_END"	    DATE		NULL,
	"VACATION_COUNT"	NUMBER		NULL
);

ALTER TABLE "VACATION"
    ADD CONSTRAINT FK_VACATION_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE CASCADE;

CREATE TABLE "ANNUAL" (
	"ANNUAL_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"ANNUAL_LEAVE"	NUMBER		NULL,
    CONSTRAINT PK_ANNUAL PRIMARY KEY(ANNUAL_NO)
);

ALTER TABLE "ANNUAL"
    ADD CONSTRAINT FK_ANNUAL_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE CASCADE;
              
CREATE TABLE "SCHEDULE" (
	"SCHEDULE_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	        NUMBER		NOT NULL,
	"SCHEDULE_TITLE"	VARCHAR2(100 BYTE)		NULL,
	"SCHEDULE_CONTENT"	VARCHAR2(2000 BYTE)		NULL,
	"SCHEDULE_START"	VARCHAR2(30 BYTE)		NULL,
	"SCHEDULE_END"	    VARCHAR2(30 BYTE)		NULL,
	"SCHEDULE_TIME_START"	VARCHAR2(30 BYTE)		NULL,
	"SCHEDULE_TIME_END"	VARCHAR2(30 BYTE)		NULL,
	"SCHEDULE_CATEGORY"	VARCHAR2(20 BYTE)		NULL,
	"SCHEDULE_STATUS"	VARCHAR2(10 BYTE)		NULL,
	"SCHEDULE_ALLDAY"	VARCHAR2(30 BYTE)		NULL,
	"SCHEDULE_COLOR"	VARCHAR2(20 BYTE)		NULL,
    CONSTRAINT PK_SCHEDULE PRIMARY KEY(SCHEDULE_NO)
);

ALTER TABLE "SCHEDULE"
    ADD CONSTRAINT FK_SCHEDULE_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE CASCADE;

CREATE TABLE "ATTENDANCE" (
	"ATT_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"ATT_START"	    VARCHAR2(20 BYTE)		NULL,
	"ATT_END"	    VARCHAR2(20 BYTE)		NULL,
	"ATT_DATE"	    VARCHAR2(20 BYTE)		NULL,
	"ATT_DAY"	    VARCHAR2(8 BYTE)		NULL,
	"ATT_STATUS"	VARCHAR2(40 BYTE)		NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY(ATT_NO)
);

ALTER TABLE "ATTENDANCE"
    ADD CONSTRAINT FK_ATTENDANCE_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE CASCADE;
              
CREATE TABLE "EMP_ADDR" (
	"EMP_ADDR_NO"	NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
    "NAME"	        VARCHAR2(50 BYTE)	NOT NULL, /* 수정 */
    "PASSWORD"      VARCHAR2(20 BYTE)   NOT NULL, /* 수정 */
	"PHONE"	        VARCHAR2(16 BYTE),
	"EMAIL"	        VARCHAR2(100 BYTE)	UNIQUE  NOT NULL, /* 수정 */
    "FAX"           VARCHAR2(20 BYTE),      /* 수정 */
    CONSTRAINT PK_EMP_ADDR PRIMARY KEY(EMP_ADDR_NO)
);

ALTER TABLE "EMP_ADDR"
    ADD CONSTRAINT FK_EMP_ADDR FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "ADDR_GROUP" (                  /* 추가 */
    "ADDR_GROUP_NO"     NUMBER NOT NULL,
    "EMP_NO"            NUMBER NOT NULL,
    "ADDR_GROUP_NAME"   VARCHAR2(36 BYTE)   NOT NULL,
    CONSTRAINT PK_ADDR_GROUP PRIMARY KEY(ADDR_GROUP_NO)
);

ALTER TABLE "ADDR_GROUP"
    ADD CONSTRAINT FK_EMP_GROUP FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE CASCADE;
              
CREATE TABLE "PERSONAL_ADDR" (              /* 추가 */
    "PERSONAL_NO"       NUMBER  NOT NULL,
    "GROUP_NO"          NUMBER      NULL,
    "ADDR_NAME"	        VARCHAR2(50 BYTE)	NOT NULL,
    "ADDR_PHONE"	    VARCHAR2(16 BYTE),
    "COMPANY"           VARCHAR2(50 BYTE),
    "EMAIL"	            VARCHAR2(100 BYTE)	NOT NULL,
    "FAX"               VARCHAR2(20 BYTE),
    "MEMO"              VARCHAR2(1000 BYTE),
    "IMPORTANT_CHECK"   VARCHAR2(1 BYTE),
    CONSTRAINT PK_PERSONAL PRIMARY KEY(PERSONAL_NO),
    CONSTRAINT CK_PERSONAL_IMPO CHECK (IMPORTANT_CHECK IN('Y', 'N'))
);

ALTER TABLE "PERSONAL_ADDR"
    ADD CONSTRAINT FK_GROUP_PERSONAL FOREIGN KEY(GROUP_NO)
        REFERENCES "ADDR_GROUP"(ADDR_GROUP_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "MAIL" (
	"MAIL_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"SENDER"	    VARCHAR2(100 BYTE)		NOT NULL, /* 수정 */
	"SUBJECT"	    VARCHAR2(100 BYTE)		NULL,    /* 수정 */
	"MAIL_CONTENT"	VARCHAR2(4000 BYTE)		NULL,
	"RECEIVER"	    VARCHAR2(60 BYTE)		NULL,
	"SEND_DATE"	    DATE		NULL,
	"SEND_STATUS"	VARCHAR2(30 BYTE)		NULL,
	"TAG_NO"	    NUMBER		NULL,
    CONSTRAINT PK_MAIL PRIMARY KEY(MAIL_NO)
);

ALTER TABLE "MAIL"
    ADD CONSTRAINT FK_MAIL_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "RECEIVERS" (
    "REC_EMP_NO"	NUMBER		NOT NULL,   /* 수정 */
	"MAIL_NO"	    NUMBER		NOT NULL,
    "READ_CHECK"    VARCHAR2(1 BYTE),
    "DELETE_CHECK"  VARCHAR2(1 BYTE),
    "RECEIVE_TYPE"  VARCHAR2(4 BYTE),
    CONSTRAINT CK_RECEIV_READ CHECK (READ_CHECK IN('Y', 'N')),
    CONSTRAINT CK_RECEIV_DELET CHECK (DELETE_CHECK IN('Y', 'N')),
    CONSTRAINT CK_RECEIV_TYPE CHECK (RECEIVE_TYPE IN('To', 'cc', 'send'))
);

ALTER TABLE RECEIVERS
    ADD CONSTRAINT FK_RECEIV_EMP FOREIGN KEY(REC_EMP_NO)    /* 수정 */
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;
              
ALTER TABLE RECEIVERS
    ADD CONSTRAINT FK_RECEIV_MAIL FOREIGN KEY(MAIL_NO)
        REFERENCES "MAIL"(MAIL_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "MAIL_ATCH" (
	"FILE_NO"	    NUMBER		NOT NULL,
	"MAIL_NO"	    NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(300 BYTE)		NULL,
	"CHANGE_NAME"	VARCHAR2(300 BYTE)		NULL,
    "MAIL_PATH"     VARCHAR2(200 BYTE)  NULL, /* 추가 */
	"UPLOAD_DATE"	DATE		NULL,
    "HAS_THUMBNAIL"     NUMBER(1)   NULL,   /* 추가 */
     CONSTRAINT PK_MAIL_ATT PRIMARY KEY(FILE_NO)
);

ALTER TABLE "MAIL_ATCH"
    ADD CONSTRAINT FK_MAIL_ATCH_MAIL FOREIGN KEY(MAIL_NO)
        REFERENCES MAIL(MAIL_NO)
              ON DELETE CASCADE;

CREATE TABLE "MAILSTATUS" (
	"MAIL_NO"	        NUMBER		NOT NULL,
	"EMP_NO"	        NUMBER		NOT NULL,
	"EMP_EMAIL"	        VARCHAR2(60 BYTE)		NULL,
	"MAIL_TYPE"	        NUMBER		NULL,
	"MAIL_READ"	        VARCHAR2(10 BYTE)		NULL,
	"MAIL_DELETE"	    VARCHAR2(10 BYTE)		NULL,
	"MAIL_IMPORTANT"	VARCHAR2(10 BYTE)		NULL,
    CONSTRAINT PK_MAILSTATUS PRIMARY KEY(MAIL_NO)
);

ALTER TABLE "MAILSTATUS"
    ADD CONSTRAINT FK_MAILSTATUS_EMP FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
              ON DELETE SET NULL;

ALTER TABLE "MAILSTATUS"
    ADD CONSTRAINT FK_MAILSTATUS_MAIL FOREIGN KEY(MAIL_NO)
        REFERENCES MAIL(MAIL_NO)
              ON DELETE CASCADE;
              
CREATE TABLE MAIL_SUMMER_IMAGE (
    MAIL_NO NUMBER,  -- 외래키
    FILESYSTEM VARCHAR2(40 BYTE)
);

ALTER TABLE "MAIL_SUMMER_IMAGE"
    ADD CONSTRAINT FK_SUMMER_MAIL FOREIGN KEY(MAIL_NO)
        REFERENCES MAIL(MAIL_NO)
              ON DELETE CASCADE;

CREATE TABLE "TAG" (
	"TAG_NO"	NUMBER		NOT NULL,
	"EMAIL"	    VARCHAR2(60 BYTE)		NULL,
	"TAG_NAME"	VARCHAR2(50 BYTE)		NULL,
	"TAG_COLOR"	VARCHAR2(20 BYTE)		NULL,
	"TAG_DATE"	DATE		NULL,
    CONSTRAINT PK_TAG PRIMARY KEY(TAG_NO)
);

CREATE TABLE "UN_CMT" (
	"UN_CMT_NO"	        NUMBER		NOT NULL,
	"ANONY_NO"	    NUMBER		NOT NULL,
	"CREATE_DATE"	    DATE		NULL,
	"UN_CMT_CONTENT"	VARCHAR2(700 BYTE)		NOT NULL,
	"STATE"	            NUMBER(1)		NULL,
	"DEPTH"	            NUMBER(1)		NULL,
	"GROUP_NO"	        NUMBER		NULL,
	"EMP_NO"	        NUMBER		NOT NULL,
    CONSTRAINT PK_UN_CMT PRIMARY KEY(UN_CMT_NO)
);

ALTER TABLE "UN_CMT"
    ADD CONSTRAINT FK_UN_CMT FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;

CREATE TABLE "ANONY" (
	"ANONY_NO"	    NUMBER		NOT NULL,
	"ANONY_TITLE"	    VARCHAR2(80 BYTE)		NULL,
	"ANONY_CONTENT"	VARCHAR2(4000 BYTE)		NULL,
    "CREATE_DATE"	DATE		NOT NULL,
	"EMP_NO"	        NUMBER		NOT NULL,
    CONSTRAINT PK_ANONY PRIMARY KEY(ANONY_NO)
);

ALTER TABLE "ANONY"
    ADD CONSTRAINT FK_ANONY FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "NOTIC" (
	"NOTIC_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60 BYTE)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000 BYTE)		NULL,
	"CREATE_DATE"	DATE		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
    "BOARD_TOP"     VARCHAR2(2 BYTE) NULL,  /* 수정 */
	"HIT"	        NUMBER		NULL,
    CONSTRAINT PK_NOTIC PRIMARY KEY(NOTIC_NO)
);

ALTER TABLE NOTIC
    ADD CONSTRAINT FK_NOTIC_EMP FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;
              
CREATE TABLE "BOARD" (
	"BOARD_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60 BYTE)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000 BYTE)		NULL,
	"CREATE_DATE"	DATE		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"HIT"	        NUMBER		NULL,
	"DEPT_NO"	    NUMBER		NOT NULL,
	"STATUS"	    NUMBER(1)		NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

ALTER TABLE BOARD
    ADD CONSTRAINT FK_EMPLOYEES_BOARD FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
            ON DELETE SET NULL;
              
CREATE TABLE "LOVES" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

ALTER TABLE LOVES
    ADD CONSTRAINT FK_LOVES_BOARD FOREIGN KEY(BOARD_NO)
        REFERENCES BOARD(BOARD_NO)
            ON DELETE CASCADE;
            
ALTER TABLE LOVES
    ADD CONSTRAINT FK_LOVES_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
            ON DELETE CASCADE;
            
CREATE TABLE "CMT" (
	"CMT_NO"	    NUMBER		NOT NULL,
	"BOARD_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"CREATE_DATE"	DATE		NULL,
	"CMT_CONTENT"	VARCHAR2(700 BYTE)		NOT NULL,
	"STATE"	        NUMBER(1)		NULL,
	"DEPTH"	        NUMBER(1)		NULL,
	"GROUP_NO"	    NUMBER		NULL,
     CONSTRAINT PK_CMT PRIMARY KEY(CMT_NO)
);

ALTER TABLE CMT
    ADD CONSTRAINT FK_CMT_BOARD FOREIGN KEY(BOARD_NO)
        REFERENCES BOARD(BOARD_NO)
            ON DELETE CASCADE;
            
ALTER TABLE CMT
    ADD CONSTRAINT FK_CMT_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
            ON DELETE SET NULL;

CREATE TABLE "UPLOAD" (
	"UPLOAD_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60 BYTE)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000 BYTE)		NULL,
	"CREATE_DATE"	DATE		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"HIT"	        NUMBER		NULL,
    CONSTRAINT PK_UPLOAD PRIMARY KEY(UPLOAD_NO)
);

ALTER TABLE UPLOAD
    ADD CONSTRAINT FK_UPLOAD_EMP FOREIGN KEY(EMP_NO)
        REFERENCES "EMPLOYEES"(EMP_NO)
              ON DELETE SET NULL;

CREATE TABLE "ATTACH" (
	"ATTACH_NO"	    NUMBER		NOT NULL,
	"UPLOAD_NO"	    NUMBER		NOT NULL,
	"EMP_NO"	    NUMBER		NOT NULL,
	"PATH"	        VARCHAR2(300 BYTE)		NULL,
	"ORIGIN"	    VARCHAR2(300 BYTE)		NULL,
	"FILESYSTEM"	VARCHAR2(300 BYTE)		NULL,
     CONSTRAINT PK_ATTACH PRIMARY KEY(ATTACH_NO)
);

-- 주희 추가
CREATE TABLE "ACCESS_LOG"(
    "ACCESS_LOG_NO"   NUMBER NOT NULL,
    "EMP_NO"          NUMBER      NOT NULL,
    "LAST_LOGIN_DATE" DATE NOT NULL     ,     -- 마지막 로그인일
     CONSTRAINT PK_ACCESS_LOG PRIMARY KEY(ACCESS_LOG_NO)
);

-- ACCESS_LOG 외래키
-- 주희 추가
ALTER TABLE ACCESS_LOG
    ADD CONSTRAINT FK_ACCESS_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES USERS(EMP_NO)
            ON DELETE CASCADE;



ALTER TABLE ATTACH
    ADD CONSTRAINT FK_ATTACH_UPLOAD FOREIGN KEY(UPLOAD_NO)
        REFERENCES UPLOAD(UPLOAD_NO)
            ON DELETE CASCADE;
            
ALTER TABLE ATTACH
    ADD CONSTRAINT FK_ATTACH_EMPLOYEES FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEES(EMP_NO)
            ON DELETE SET NULL;
            
CREATE TABLE SUMMERNOTE_IMAGE (
    UPLOAD_NO NUMBER,  -- 외래키
    FILESYSTEM VARCHAR2(40 BYTE)
);

ALTER TABLE "SUMMERNOTE_IMAGE"
    ADD CONSTRAINT FK_SUMMER_UPLOAD FOREIGN KEY(UPLOAD_NO)
        REFERENCES UPLOAD(UPLOAD_NO)
              ON DELETE CASCADE;        
              
/* 주희 추가 */
CREATE TABLE PROF_IMAGE(
    IMG_NO NUMBER NOT NULL,
    EMP_NO NUMBER NOT NULL,  -- 외래키
    PROF_PATH VARCHAR2(300 BYTE) NULL,       -- 파일의 경로
    PROF_ORIGIN VARCHAR2(300 BYTE) NULL,
    PROF_FILESYSTEM VARCHAR2(40 BYTE)
);

ALTER TABLE PROF_IMAGE
  ADD CONSTRAINT FK_PROF_IMAGE
      FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO)
           ON DELETE CASCADE              


-- 결재문서

DROP SEQUENCE ACCESS_LOG_SEQ;/* 주희 추가*/

DROP SEQUENCE PROF_SEQ; /* 주희 추가*/

DROP SEQUENCE APPROVAL_SEQ;

DROP SEQUENCE ANNUAL_SEQ;
DROP SEQUENCE ATT_SEQ;
DROP SEQUENCE SCH_SEQ;

DROP SEQUENCE POSITION_SEQ;
DROP SEQUENCE DEPT_SEQ;
DROP SEQUENCE EMP_SEQ;

DROP SEQUENCE EMP_ADDR_SEQ;
DROP SEQUENCE ADDR_GROUP_SEQ; /* 추가 */
DROP SEQUENCE PERSONAL_ADDR_SEQ; /* 추가 */

DROP SEQUENCE MAIL_SEQ;
DROP SEQUENCE MAIL_ATT_SEQ;
DROP SEQUENCE TAG_SEQ;

DROP SEQUENCE ANONY_SEQ;
DROP SEQUENCE AN_CMT_SEQ;
DROP SEQUENCE UPLOAD_SEQ;
DROP SEQUENCE ATTACH_SEQ;
DROP SEQUENCE NOTIC_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE CMT_SEQ;




CREATE SEQUENCE APPROVAL_SEQ NOCACHE;

CREATE SEQUENCE ANNUAL_SEQ NOCACHE;
CREATE SEQUENCE ATT_SEQ NOCACHE;
CREATE SEQUENCE SCH_SEQ NOCACHE;

CREATE SEQUENCE POSITION_SEQ NOCACHE;
CREATE SEQUENCE DEPT_SEQ START WITH 20 INCREMENT BY 10 NOCACHE;
CREATE SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;

CREATE SEQUENCE EMP_ADDR_SEQ NOCACHE;
CREATE SEQUENCE ADDR_GROUP_SEQ NOCACHE; /* 추가 */
CREATE SEQUENCE PERSONAL_ADDR_SEQ NOCACHE; /* 추가 */
   
CREATE SEQUENCE MAIL_SEQ NOCACHE;
CREATE SEQUENCE MAIL_ATT_SEQ NOCACHE;
CREATE SEQUENCE TAG_SEQ NOCACHE;

CREATE SEQUENCE ANONY_SEQ NOCACHE;
CREATE SEQUENCE AN_CMT_SEQ NOCACHE;
CREATE SEQUENCE UPLOAD_SEQ NOCACHE;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;
CREATE SEQUENCE NOTIC_SEQ NOCACHE;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
CREATE SEQUENCE CMT_SEQ NOCACHE;
CREATE SEQUENCE PROF_SEQ NOCACHE; /* 주희 추가 */
CREATE SEQUENCE ACCESS_LOG_SEQ NOCACHE; /* 주희 추가 */


INSERT INTO DEPARTMENTS(DEPT_NO , DEPT_NAME) VALUES(DEPT_SEQ.NEXTVAL , '인사총무부');
INSERT INTO DEPARTMENTS(DEPT_NO , DEPT_NAME) VALUES(DEPT_SEQ.NEXTVAL , '재무회계부');
INSERT INTO DEPARTMENTS(DEPT_NO , DEPT_NAME) VALUES(DEPT_SEQ.NEXTVAL , '영업부');

INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '대표');
INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '부장');
INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '차장');
INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '과장');
INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '대리');
INSERT INTO POSITION(JOB_NO , JOB_NAME) VALUES(POSITION_SEQ.NEXTVAL , '사원');

INSERT INTO EMPLOYEES 

--SELECT TO_NUMBER(TO_CHAR(SYSDATE,'YYMM')) || LPAD(EMP_SEQ.NEXTVAL,4,0)
--  FROM DUAL;
--  
COMMIT;
--  
