-- 다대다 관계
    --1.여러 학생이 여러 과목을 신청하는 다대다관계
    --2.학생-과목 직접적인 다대다관계 설정은 불가능
    --3.학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
    
 -- 참고
 -- 외래키 제약조건을 무시하고 테이블 삭제
 -- 순서에 상관없이 삭제할 수 있다
    DROP TABLE STUDENT CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE STUDY  CASCADE CONSTRAINTS;
 

-- 테이블 삭제

DROP TABLE STUDENT;
DROP TABLE SUBJECT;
DROP TABLE STUDY;

-- 학생테이블 생성
CREATE TABLE STUDENT(
    STU_NO VARCHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(15 BYTE) NULL,
    STU_AGE NUMBER(3) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);    


-- 과목테이블 생성
CREATE TABLE SUBJECT(
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(10 BYTE) NULL,
    SUB_PROFNAME VARCHAR2(15 BYTE) NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
 );
 
 
 -- 수강신청 테이블
 CREATE TABLE STUDY(
    STD_NO NUMBER(1) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_STUDY PRIMARY KEY(STU_NO),
    CONSTRAINT FK_STUDY_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_STUDY_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
 );   
    