
-- VARCHAR와 CHAR는 반드시 크기 지정해야한다
-- 


-- 테이블 삭제
DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;



-- 부서 테이블
CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE)NULL
 );
 
 
 -- 프로젝트 테이블
 CREATE TABLE PROJECT(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL
 );
 

 
 
 
 -- 사원 테이블
 CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE) NULL, --외래키
    POSITION CHAR(10 BYTE) NULL,
    NAME VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL
 );
 
 -- 프로젝트 진행 테이블
 CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER NULL,-- 외래키
    PJT_NO NUMBER NULL,-- 외래키
    PJT_STATE NUMBER NOT NULL
    
);    

--기본 키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
 
 ALTER TABLE PROJECT
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY(PJT_NO);
    
 ALTER TABLE EMPLOYEE
     ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO);
     
 ALTER TABLE PROCEEDING
     ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY(PCD_NO);
    
    
 
 -- 외래키 추가
 ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
     REFERENCES DEPARTMENT(DEPT_NO);
     
 ALTER TABLE PROCEEDING     
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO)
      REFERENCES EMPLOYEE(EMP_NO);
      
 ALTER TABLE PROCEEDING     
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY(PJT_NO)
      REFERENCES PROJECT(PJT_NO);
        
     
 
  -- 외래키 제거 방법
  -- DEPARTMENT 테이블의 DEPT_NO칼럼을 참조하는 외래키 제약조건을 제거해야
  -- DEPARTMENT 테이블의 DEPT_NO칼럼에 추가된 기본키 제약조건을 제거할 수 있다
 ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;

 
 -- 기본키 제거 방법(테이블 삭제 순서와 같다)
 -- FK에 의해서 참조되고 있는 PK는 제거할 수 없다
 -- 먼저 FK를 제거해야 한다
 ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT; --EMPLOYEE의 FK를 먼저 제거해야 실행 가능
 
 -- 기본키에 이름X
 -- 기본키는 테이블당 하나만 들어갈 수 있으므로 이렇게 지울 수 있음
 ALTER TABLE DEPARTMENT
    DROP PRIMARY KEY; 
    
 -- 기본키 이름을 알 경우
 ALTER TABLE PROCEEDING
    DROP CONSTRAINT PK_PROCEEDING;
 


 
 
 
 
 
 
 