DROP TABLE MEMBER_LOG;
DROP TABLE MEMBER;


CREATE TABLE MEMBER(
    MEMBER_NO NUMBER NOT NULL,
    ID VARCHAR2(30 BYTE) NOT NULL,
    PW VARCHAR2(30 BYTE) NOT NULL,
    NAME VARCHAR2(30 BYTE) NULL,
    PHONE VARCHAR2(15 BYTE) NULL
);


CREATE TABLE MEMBER_LOG(
    LOG_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NULL,
    LOGIN DATE NULL
);
